// Replace this entire code
// With something else

async function main() {
    return new Promise<number>((resolve) => resolve(4));
}

main()
    .then((success) => success)
    .catch((err) => console.error(err));
